feat: use sarif report to create pr comment and vuln report
ref: https://github.com/nofusscomputing/centurion_erp/pull/1202 https://github.com/nofusscomputing/centurion_erp/pull/1201

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -389,136 +389,52 @@ jobs:
           path: trivy-results.sarif
 
 
-      - name: Run Trivy vulnerability scanner (json Report)
-        if: inputs.DOCKER_SCAN_IMAGE_VULNERABILITY
-        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25    # v0.36.0
-        with:
-          image-ref: '${{ inputs.DOCKER_BUILD_REGISTRY }}/${{ inputs.DOCKER_BUILD_IMAGE_NAME }}:${{ inputs.DOCKER_BUILD_IMAGE_TAG }}'
-          format: 'json'
-          output: 'image-scan-results.json'
-          severity: 'LOW,MEDIUM,HIGH,CRITICAL'
-          vuln-type: 'os,library'
-          scanners: vuln
-          ignore-unfixed: false
-
-      - name: Upload scan results
-        if: inputs.DOCKER_SCAN_IMAGE_VULNERABILITY
-        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a    # v7.0.1
-        with:
-          name: container-scan-results-json
-          path: image-scan-results.json
-
-
       - run: |
-          ls -la
+          echo "${PWD}" || echo "couldnt PWD";
 
-      - name: Create Vulnerabilities (Critical/High)
-        if: inputs.DOCKER_SCAN_IMAGE_VULNERABILITY
+          echo "1";
+
+          ls -la;
+
+          echo "2";
+
+          mkdir -p ${{ runner.temp }}/_github_home/ || echo "could not make";
+
+          echo "2.1";
+
+          ls -la ${{ runner.temp }}/_github_home/;
+
+          echo "3";
+
+          mv -f trivy-results.sarif ${{ runner.temp }}/_github_home/trivy-results.sarif;
+
+          echo "4";
+
+          ls -la ${{ runner.temp }}/_github_home/;
+
+
+      - name: Convert Sarif -> Markdown
+        if: success() || failure()
+        id: sarif-to-markdown
+        uses: 11notes/action-sarif-to-markdown@bc689850bd33a1037ea1d0a609ab4ea14b3c4396   # v1.2.0
+        with:
+          sarif_file: trivy-results.sarif
+
+
+      - name: Create Report Artifact
         run: |
-          echo "[Debug] jq -r '.Results'=$(jq -r '.Results' scan-results.json)";
+          ls -la ${{ runner.temp }}/_github_home/sarif.md;
 
-          not_empty="";
-
-          if [ "$(jq -r '.Results' scan-results.json)" != 'null' ] && [ "0$(jq -r '.Results' scan-results.json)" != '0' ]; then
-
-            if [ "$(jq -r '.Results[] | .Vulnerabilities' scan-results.json)" != 'null' ] && [ "0$(jq -r '.Results[] | .Vulnerabilities' scan-results.json)" != '0' ]; then
-
-              not_empty="$(jq -r '.Results[] | .Vulnerabilities[]' scan-results.json)";
-
-            fi
-
-          fi
-
-          echo "[Debug] not_empty=${not_empty}";
-
-
-          jq -r '
-          [
-          "# Image Scan Results",
-          "",
-          "**Scan Date:** _" + ( .CreatedAt // "" ) + "_",
-          "**Image:** _" + ( .ArtifactName // "" ) + "_",
-          "**OS:** _" + ( .Metadata.OS.Family // "" ) + " " + ( .Metadata.OS.Name // "" ) + "_",
-          ""
-          ] | join("\n")
-          ' image-scan-results.json > vulnerability-report.md
-
-          if [ "$not_empty" ]; then
-            jq -r '
-            def hr(severity):
-            if severity == "HIGH" or severity == "CRITICAL" then true else false end;
-            def to_md:
-            "| " + (.VulnerabilityID // "") + " | " + (.PkgName // "") + " | " + (.InstalledVersion // "") + " | " + (.Severity // "") + " | " + (.Title // "") + " |";
-            [
-            "## High and Critical Vulnerabilities",
-            "",
-            "| Vulnerability ID | Package | Version | Severity | Description |",
-            "| --------- | ----- | ----- | ----- | -------|",
-            (.Results[] | .Vulnerabilities[] | select(hr(.Severity)) | to_md),
-            ""
-            ] | join("\n")
-            ' image-scan-results.json >> vulnerability-report.md
-
-          else
-
-            echo "**Nothing Found**" >> vulnerability-report.md
-
-          fi;
-
-
-
-      - name: Create Full Vulnerabilities
-        if: inputs.DOCKER_SCAN_IMAGE_VULNERABILITY
-        run: |
-          echo "[Debug] jq -r '.Results'=$(jq -r '.Results' scan-results.json)";
-
-          not_empty="";
-
-          if [ "$(jq -r '.Results' scan-results.json)" != 'null' ] && [ "0$(jq -r '.Results' scan-results.json)" != '0' ]; then
-
-            if [ "$(jq -r '.Results[] | .Vulnerabilities' scan-results.json)" != 'null' ] && [ "0$(jq -r '.Results[] | .Vulnerabilities' scan-results.json)" != '0' ]; then
-
-              not_empty="$(jq -r '.Results[] | .Vulnerabilities[]' scan-results.json)";
-
-            fi
-
-          fi
-
-          echo "[Debug] not_empty=${not_empty}";
-
-
-          jq -r '
-          [
-          "# Full Image Scan Results",
-          "",
-          "**Scan Date:** _" + ( .CreatedAt // "" ) + "_",
-          "**Image:** _" + ( .ArtifactName // "" ) + "_",
-          "**OS:** _" + ( .Metadata.OS.Family // "" ) + " " + ( .Metadata.OS.Name // "" ) + "_",
-          ""
-          ] | join("\n")
-          ' image-scan-results.json > full-vulnerability-report.md
-
-          if [ "$not_empty" ]; then
-            jq -r '
-            def hr(severity):
-            if severity == "HIGH" or severity == "CRITICAL" then true else false end;
-            def to_md:
-            "| " + (.VulnerabilityID // "") + " | " + (.PkgName // "") + " | " + (.InstalledVersion // "") + " | " + (.Severity // "") + " | " + (.Title // "") + " |";
-            [
-            "## Vulnerabilities",
-            "",
-            "| Vulnerability ID | Package | Version | Severity | Description |",
-            "| --------- | ----- | ----- | ----- | -------|",
-            (.Results[] | .Vulnerabilities[] | select(.Severity) | to_md),
-            ""
-            ] | join("\n")
-            ' image-scan-results.json >> full-vulnerability-report.md
-
-          else
-
-            echo "**Nothing Found**" >> full-vulnerability-report.md
-
-          fi;
+          echo "## Docker Image Scan" > vulnerability-report.md;
+          echo "" >> vulnerability-report.md;
+          echo "- **Image:** ${{ inputs.DOCKER_BUILD_REGISTRY }}/${{ inputs.DOCKER_BUILD_IMAGE_NAME }}:${{ inputs.DOCKER_BUILD_IMAGE_TAG }}" >> vulnerability-report.md;
+          echo "" >> vulnerability-report.md;
+          echo ">[!tip]" >> vulnerability-report.md;
+          echo ">" >> vulnerability-report.md;
+          echo "> _If this report shows nothing, it means there was nothing found._" >> vulnerability-report.md;
+          echo "" >> vulnerability-report.md;
+          echo -n "#" >> vulnerability-report.md;
+          cat ${{ runner.temp }}/_github_home/sarif.md >> vulnerability-report.md;
 
 
       - name: Upload scan results
@@ -528,12 +444,13 @@ jobs:
           name: docker-vulnerability-report
           path: vulnerability-report.md
 
-      - name: Upload scan results
-        if: inputs.DOCKER_SCAN_IMAGE_VULNERABILITY
-        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a    # v7.0.1
-        with:
-          name: docker-vulnerability-report-full
-          path: full-vulnerability-report.md
+
+      # - name: Upload scan results
+      #   if: inputs.DOCKER_SCAN_IMAGE_VULNERABILITY
+      #   uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a    # v7.0.1
+      #   with:
+      #     name: docker-vulnerability-report-full
+      #     path: full-vulnerability-report.md
 
 
 
@@ -651,7 +568,7 @@ jobs:
         if: inputs.DOCKER_SCAN_IMAGE_VULNERABILITY
         uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c    # V8.0.1
         with:
-          name: docker-vulnerability-report-full
+          name: docker-vulnerability-report
 
 
       - uses: dtinth/markdown-report-action@v1
@@ -659,7 +576,7 @@ jobs:
         with:
           name: Docker Vulnerability Report
           title: Vulnerability Report
-          body-file: full-vulnerability-report.md
+          body-file: vulnerability-report.md
 
 
 
